Math magicians: components
ragangithub/math-magicians pull request #2
Opened 2023-05-29 18:53 UTC by ragangithub

- Deleted all the boilerplate from Create React App (text, images, styles).
- Created a new directory called Components.
- created a new Calculator.js file.
- Used functional components

2023-05-29 19:58 UTC, KanzaTahreem requested changes
# Changes Required 🔁

Hi @ragangithub 🙋‍♀️

Good job so far! I really appreciate the effort you put in! 
**_However, there are few things that still need to be fixed. But you are almost there!_** 💪 🏁

![so_close](https://user-images.githubusercontent.com/99715640/211022680-440a1bb1-4281-4acb-8dbc-3442fe509063.gif)

## Highlights 🎯

There are some excellent points that you have made perfectly. Keep up the great work! 👏
- ✅ Deleted boilerplate, perfect!
- ✅ Great job with CSS
- ✅ Descriptive PR and README file
- ✅ Correct Linters


## Required Changes 🛑

> _Please keep in mind that your long hours of work is appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. 😄_


_Please check the comments under the review._

## Optional suggestions ❕
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-29 19:58 UTC, KanzaTahreem commented on src/components/calculator.js
- [ ] Kindly make sure to use PascalCase for component file names. It is recommended to use PascalCase for component file names in React to adhere to best practices and enhance the overall maintainability of the codebase.💪 For example, if you have a component called "_header menu_," the corresponding file name will be `HeaderMenu.js` or `HeaderMenu.jsx` 🤓⛏ It is also mentioned in the project requirements 👇

  > _Inside `components`, create a new `Calculator.js` file._
  
  You can learn more about naming convention from the following 👇
 - [react/jsx-pascal-case](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-pascal-case.md)
 - [JSX In Depth](https://legacy.reactjs.org/docs/jsx-in-depth.html#user-defined-components-must-be-capitalized)
 - [React/JSX Style Guide](https://github.com/airbnb/javascript/tree/master/react#naming)

2023-05-29 19:58 UTC, KanzaTahreem commented on src/components/display.js
- [ ] Similarly here, Can you use `Display.js` or `Display.jsx` for naming the component file because of the above mentioned reason ?📌

2023-05-30 07:07 UTC, ragangithub commented
- Used PascalCase
- Fixed Linter errors

2023-05-30 07:19 UTC, abdallahmalima approved these changes
Hi @ragangithub , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Remove boilerplate ✔
- Components Directory✔
- Calculator.js file✔
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-30 08:41 UTC, merged